services:
  app:
    container_name: rails-single-app
    build:
      context: .
      dockerfile: tmp.ruby.dockerfile
      target: dev
      args:
        RUBY_VERSION: 3.3
        NODE_VERSION: 22
        WORKING_DIR: /workspace/app
    tty: true
    restart: on-failure
    ports:
      - 3000:3000
      - 4200:4200
      - 6006:6006
    networks:
      - single_app
    volumes:
      - ..:/workspace/app
  local_stack:
    container_name: local_stack_container
    build:
      context: .
      dockerfile: tmp.localstack.dockerfile
      args:
        LOCALSTACK_VERSION: latest
  cognito:
    container_name: cognito_container
    build:
      context: .
      dockerfile: tmp.cognito.dockerfile
      args:
        MOTO_VERSION: 5.0.25
    ports:
      - 4000:4000
    networks:
      - single_app
    restart: on-failure


networks:
  single_app: {}

volumes:
  db_data: {}
